### ISSUE TITLE
[Test issue] Trying out a task list for release stuff

### ISSUE THREAD

**Issue by ghost** [microprofile/microprofile-marketing#551]
- [x] Update MicroProfile presentation and save it in the right folder (technical person) https://github.com/eclipse/microprofile-marketing/issues/547
- [x] Import the presentation to the landing page and resources page of the website https://github.com/eclipse/microprofile-marketing/issues/547
- [x] Draft a release announcement blog post using template (technical person)https://github.com/eclipse/microprofile-marketing/issues/548
- [x] Create release announcement design card https://github.com/eclipse/microprofile-marketing/issues/546
- [x] Update MicroProfile homepage with release announcement design card
- [x] Edit/Publish release announcement blog post on the MicroProfile Blog
- [x] Announce release on social media using Hootsuite (Twitter, Linkedin, Facebook) https://github.com/eclipse/microprofile-marketing/issues/542
- [x] Write an update to the MP Community Forum about the release
- [x] Update the MP Calendar with the Release Date (committer)

Note: when I checked on August 12:

It appears the 4.1 presentation is in the[ latest version folder here](https://drive.google.com/drive/folders/1VheJD9sJBiwfXSH1Lbc-eQtVuz4BFM6d?usp=sharing) and it appears the 4.0 presentation is in the [2020 Releases folder here](https://drive.google.com/drive/folders/1WeFgN1SDzf6Z_9fN9308DACBxr1Ukwgz?usp=sharing)

It appears the Tweet with the designed social card about the announcement has been[ published here](https://twitter.com/MicroProfileIO/status/1423317267882905600?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1423317267882905600%7Ctwgr%5E%7Ctwcon%5Es1_c10&ref_url=https%3A%2F%2Fpublish.twitter.com%2F%3Fquery%3Dhttps3A2F2Ftwitter.com2FMicroProfileIO2Fstatus2F1423317267882905600widget%3DTweet): 

And that the Microprofile.io homepage has been updated and the[ blog announcement published](https://microprofile.io/2021/08/05/microprofile-4-1-is-now-available/).

**Comment by edbratt** [comment]
Debbie, If you haven't used them, you might also want to look at GitHub project boards. They are quite useful when there are lots of relatively independent tasks -- and the view / presentation formats are pretty nice to work with.

**Comment by ghost** [comment]
Thanks @edbratt  Doesn't look like I would have the right access level to create an organization or repository level project board - just a personal one.  From what I can tell only Pull Requests would be automated into the kan ban style view (to do, in progress, done) and I think we'd have to add individual cards to track issue progress. my goal is to reduce the number of  "things" and issues we have for each task. Will investigate some more!

**Comment by edbratt** [comment]
You would need committer access to set up a project. I'd need to review the documentation to see what can be done by committers vs. non-committers. I suspect, without commit rights, not much.

**Comment by aeiras** [comment]
Debbie and Ed, 

I have created the Releases project (it was needed anyways)  https://github.com/eclipse/microprofile-marketing/projects

Once we make every active contributor  (Ed and I task) able to assign issues to projects & to people, (no need for committer access) tickets can follow a clear path for all work on Releases. 

Debbie, I really like the template you have created on this ticket that holds all the release tickets into 1 place as well. 
Note that it is important that every task holds a ticket as a lot of work and exchanges take place and will be buried if using just 1 ticket.

**Comment by ghost** [comment]
Hi @aeiras  I can see that we would need individual tasks (we don't currently have that by the way, we have several but not one per each which is also why it can be confusing to find a conversation about the blog for example, if the conversation took place in an issue about designing the social card). But I think having the overview issue as a checklist that is linked to each individual issue for the release, and also show whether each one has been completed or not on a single screen can be very useful. Especially since in the case of a release, we would need to do the same steps each time. Then when we are discussing what needs doing for the release, we'd just pull up this checklist issue that gives us an overview and can click on the individual issues/tasks as necessary.

I can see this overview/checklist style issue coming in handy for other things we do that are connected, too. So while it may not reduce the total number of issues created, it gives us a way to find the ones related to a topic easily, and see progress toward that topic's completion.

If we can also get a kan ban style view that the projects allow at some point, that could also help us see progress of everything on one screen - what still needs "to do", what's "in progress", and what's done.

**Comment by aeiras** [comment]
Yes. I really love the overview template you created. + 1 from to put it into action. 
To broaden the scope,  you could choose to send this ticket to the marketing forum.  The Release Kaban is now available to hold all tickets for the tasks based on your work.

Amazing timing. If you set the template today, we can use it. 
We only just got done with the 4.1 blog review. :)  the team is  moving to the final tasks. 

Related to clean up and easier navigation, please, at your leisure, if you could look at the projects (currently 9 created), maybe you could see what other tasks are complex in part that could use an overview template similar to the one you created for the Releases, AMAZING!

**Comment by aeiras** [comment]
Kaban https://github.com/eclipse/microprofile-marketing/projects/9

**Comment by aeiras** [comment]
@debbiehoffman, 

Are you ok with the creation of the git issue template in this repo as shown above?
If blocked, please let us know how to help. 

+1 on moving forward with the list you have provided based on tickets and on mp 4.1 release work.

**Comment by ghost** [comment]
Do you mean add it here? https://github.com/eclipse/microprofile-marketing/projects/9  It doesn't seem to let me do anything but view that. @aeiras

**Comment by aeiras** [comment]
nope, Debbie. 
These are 2 examples of templates we ought to create with your list that will be used each time a release is coming. 

https://github.com/microprofile/microprofile-wg/issues/new/choose

**Comment by ghost** [comment]
@aeiras  I won't be able to create template tasks for those without having a list of what we do for Compatible Certification Request or Specification Review Issue, as I don't know what those tasks would be. If someone would like to make a list of those items or point me to an existing documentation that shows the process (like we have for marketing releases) I could create them.

**Comment by aeiras** [comment]
Hola @debbiehoffman, 

The steps are the ones written in the marketing google doc that is welcoming review. Already used by Emily and Edwin. Every ticket created that you linked to the above list is part of the pilot. 

Happy to answer more questions on today's discussion.

**Comment by edbratt** [comment]
According to the GitHub docs -- templates need to be set up by someone with config/owner permission on repositories. For the github.com/eclipse/microprofile-marketing repository -- does anyone have that role, or is this reserved to Eclipse administrators (i.e. we'd want to file an Eclipse bugzilla ticket).
[Here is the GitHub doc page on Templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository).
The templates themselves are just markdown. I just noticed there is an emerging feature to create a form page -- that might be useful but I don't know what the 'beta' restrictions are.
So -- one task will be to finalize the markdown file (probably just a copy of the file above); then separately, we need to enable this on the right repository.

**Comment by Emily-Jiang** [comment]
It is same as other files. Just create a PR and committers can merge in the PR after the approval.

**Comment by ghost** [comment]
@Emily-Jiang  would I just go here https://github.com/eclipse/microprofile-marketing/pulls  and do "new pull request" and ask that someone take the checklist and turn it into a template in the marketing repository?

**Comment by Emily-Jiang** [comment]
In your PR, you create the template yourself. If you have issues, I can create a PR so that you know how to do it in the future. Just let me know @debbiehoffman

**Comment by ghost** [comment]
hi @Emily-Jiang  I have no idea how to do a PR. Can you help me with that or create the PR so we can set up the template issue?

**Comment by cesarhernandezgt** [comment]
> hi @Emily-Jiang I have no idea how to do a PR. Can you help me with that or create the PR so we can set up the template issue?

Hi @debbiehoffman , in case still need it, this is the documentation I merge a couple of months ago with details on how to create a PR on any microprofile related GitHub project: https://github.com/eclipse/microprofile/blob/master/how-to-pr.adoc

**Comment by ghost** [comment]
> https://github.com/eclipse/microprofile/blob/master/how-to-pr.adoc

@cesarhernandezgt  I have reviewed that before and it's still not detailed enough for me to follow. Step one says "If it’s the first time you are going to work on a repository: Fork into your github account."
I don't know how to fork.
I don't use github for anything but MP marketing.

I created the test github issue that shows how it could look as a template for releases. If someone else who knows how to use github fully could please do the github work to make it a reality and so we can use the template (@Emily-Jiang  ?)  it would be much more efficient than me continuing to try and figure it out - it's literally a different language for me :)

**Comment by Emily-Jiang** [comment]
@debbiehoffman no worries. I will take what you have got in this issue and create a PR with the template as you will need to learn git from scratch. Since in this PR, normally you just need to open issues and comment on issues, PRs are very rarely used.

**Comment by Emily-Jiang** [comment]
@debbiehoffman here is the [PR](https://github.com/eclipse/microprofile-marketing/pull/589) . Please check the list to see whether I list all the information in this issue.
