### ISSUE TITLE
[Consolidated] Documentation Tasks Ready for Wiki Page Creation

### ISSUE THREAD

**Issue by ghost** [microprofile/microprofile-marketing#586]
- [ ] Documentation Zoom Admin #492 - Documentation created in a google doc. Someone with github skills needs to do the pr/wiki creation.
- [ ] https://github.com/eclipse/microprofile-marketing/issues/545 -The Wiki has been updated. This task should be closed.
- [x] https://github.com/eclipse/microprofile-marketing/issues/483
- [x] https://github.com/eclipse/microprofile-marketing/issues/469 -Tagged @mehmandarov requesting he turn it into a Wiki based on past comments that he might do so. Debbie trying to accept ‘write’ access to make edits directly to the wiki page https://github.com/microprofile/microprofile-wg/wiki
- [x] https://github.com/eclipse/microprofile-marketing/issues/469

**Comment by aeiras** [comment]
@debbiehoffman, 

Neha said she will help with the transfer into a wiki the Stewards Onboarding. 
Will close ticket and leave that ticket open for that work. 

Thank you for rocking this group tickets, so helpful during end of the year review. 

[Documentation] Mktg Call Monthly Stewards Onboarding #469
