### ISSUE TITLE
Release MicroProfile 5.0 on 7th Dec

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#607]
- [x]  Update MicroProfile presentation and save it in the right folder (technical person) [example here](https://github.com/eclipse/microprofile-marketing/issues/547) <br/>
- [ ] Import the presentation to the landing page and resources page of the website<br/>
- [x] Draft a release announcement blog post using template (technical person) [example here](https://github.com/eclipse/microprofile-marketing/issues/548)<br/>
- [ ] Create release announcement design card [See example here](https://github.com/eclipse/microprofile-marketing/issues/546) <br/>
- [ ] Update MicroProfile homepage with release announcement design card<br/>
- [x] Edit/Publish release announcement blog post on the MicroProfile Blog<br/>
- [ ] Announce release on social media using Hootsuite (Twitter, Linkedin, Facebook) [example here](https://github.com/eclipse/microprofile-marketing/issues/542)<br/>
- [ ] Write an update to the MP Community Forum about the release<br/>
- [ ] Update the MP Calendar with the Release Date (committer)

**MPWG Paid Services step for MP 5 Release**:

- [ ] EF MP 5 release announcement using the EF channels. https://github.com/eclipse/microprofile-marketing/issues/619

**Comment by Emily-Jiang** [comment]
I would like to target this release for 6th Dec so that we can announce it on JakartaOne Live on 7th Dec.

**Comment by Emily-Jiang** [comment]
EMO: please announce this release.

**Comment by aeiras** [comment]
@emecas, 

Thank you for volunteering to steer the Release Announcement written by the EF. 

**Processing tasks**

- [ ] Create a new git issue to inform the EF team of the release date by adding Clark' git ID to that ticket https://github.com/eclipse/microprofile-marketing/wiki/Eclipse-Foundation-Team-GitHub-IDs 
- [ ] in that ticket,  (added to the template tasks with link) I have added it under paid-services.  
- [ ] We need to request that the Announcement draft be provided for MicroProfilers' review  in word version with Suggestive Mode access at least 3 days (avoid a Friday delivery) before Dec. 6th
- [ ] We will insert our Technical blog to that paid release, make sure to state it in the ticket
- [ ] The EF can use the https://groups.google.com/g/microprofile-marketing to submit the release for review. It is your job to update that ticket you will create with such EF updates. 
- [ ] that release will be copy/paste imported into the MP blogs.  Either the EF becomes a contributor of MP blog (follows the guidelines) and they do that import  or we import the paid-announcement as an original. Both options must have the link of the actual release post. https://github.com/microprofile/wpsite   

Questions, shoot and thanks, Emerson!

**Comment by emecas** [comment]
@aeiras, I don't have permissions in this repository to mark the tasks as 1 to 4 as done,  then please see my comments below for each related subject.
 
> @emecas,
> 
> Thank you for volunteering to steer the Release Announcement written by the EF.
> 
> **Processing tasks**
> 
>     * [ ]  Create a new git issue to inform the EF team of the release date by adding Clark' git ID to that ticket https://github.com/eclipse/microprofile-marketing/wiki/Eclipse-Foundation-Team-GitHub-IDs
> 
 Done: https://github.com/eclipse/microprofile-marketing/issues/619

>     * [ ]  in that ticket,  (added to the template tasks with link) I have added it under paid-services.
> 

I am not sure about what link including, but I added the single task under paid-services to the created issue,  may you provided what link you meant here ? then I could update it

>     * [ ]  We need to request that the Announcement draft be provided for MicroProfilers' review  in word version with Suggestive Mode access at least 3 days (avoid a Friday delivery) before Dec. 6th
> 

Done

>     * [ ]  We will insert our Technical blog to that paid release, make sure to state it in the ticket
> 

Done

>     * [ ]  The EF can use the https://groups.google.com/g/microprofile-marketing to submit the release for review. It is your job to update that ticket you will create with such EF updates.
>

WIP
 
>     * [ ]  that release will be copy/paste imported into the MP blogs.  Either the EF becomes a contributor of MP blog (follows the guidelines) and they do that import  or we import the paid-announcement as an original. Both options must have the link of the actual release post. https://github.com/microprofile/wpsite
> 

TBD

> 
> Questions, shoot and thanks, Emerson!

**Comment by aeiras** [comment]
![image](https://user-images.githubusercontent.com/10731224/143296506-9ae6a5cf-fb71-43b0-a9a5-e4baed36ca67.png)
Emerson, 
I added ticket 619 to the main template above. Great stuff on that ticket. 
Will you also be the one using the technical template to start the release blog? I will be happy to review it once you, emily and Edwin are happy with first draft. 

@TetianaFTV, 
earlier this fall, you volunteered to help with logistics with MP 5. updates as done for last Dec release. Can you still own that?  Ideally, we could invite someone else from the members who are comfortable with Wordpress updates to shadow you so that they can help on next release and be a trainee on this one. :)

**Comment by Emily-Jiang** [comment]
@aeiras I have drafted [MicroProfile 5.0 blog](https://microprofile.io/wp-admin/post.php?post=6935&action=edit) . @TetianaFTV, will you be able help with inserting the image (can be found on [slide](https://docs.google.com/presentation/d/1PfXEOJzy8v2kGRudvknPox5elRasewv3MBeV0P4Rk6M/edit#slide=id.ge6794d7fa1_0_0) 8.  @rstjames please see the checklist in the issue for social card design and website updates.

I made a start on the slide deck [here](https://docs.google.com/presentation/d/1PfXEOJzy8v2kGRudvknPox5elRasewv3MBeV0P4Rk6M/edit#slide=id.ge6794d7fa1_0_0). The slide 8 and onwards need to be updated. @ederks85 will you be able to do the rest slides?

We need to go through the checklist this week to prepare most of the content.

**Comment by aeiras** [comment]
Hey amazing Emily, 

To provide feedback on the infra release, the document must be a google document to welcome my suggestive edit. Remember when we import stuff to wordpress in releases, it is only after the google document has been reviewed. 
Can you get that document imported to google doc for me by tomorrow AM? I will be happy to provide feedback via that method by the end of tomorrow. 

Please note that we want the release to be authored by you, Edwin and Emerson.  So the authors are 3 and 2 editors  Tetiana (publisher) & me (editor) 

A reminder that TT won't be helping on this release with the media, website or design. We stated earlier this summer that we wish for another member to help on MP 5 release to enable the onboarding and scaling of such tasks with respect to Releases.  
Tetiana volunteered back then to help once again on this release if it didn't hit X-Mas.  It doesn't, so we are ok, yeay!!
 Ideally, maybe Vince chooses to become a release Trainee alongside with Tetiana. Vince has no access to hootsuite and the website and can do everything Ryan and Tetiana can :) Lets' see if he wishes to do this for MP 5.

**Comment by Emily-Jiang** [comment]
@aeiras the blogs and slides are https://drive.google.com/drive/folders/1XqoNB9kEL9dpKxjHq71a4CfmBx1vjt3Z for MicroProfile 5.0 release.

**Comment by emecas** [comment]
Thank you @Emily-Jiang  for grantting me access to the draft document, I just finished reading it and adding some comments and suggestions. @aeiras @ederks85 feel free to review

**Comment by aeiras** [comment]
wonderful Emerson. 
@ederks85 please go into the draft and adjust at will. pull me into review via this git issue, after you have completed your review. 
The 3 of you are the authors of the document and will be listed as such. 

Thank you, Emily for putting it into the word doc. :)

**Comment by aeiras** [comment]
@emecas, 
I released during the review last night that you Emerson didn't have Edit access to help publish and edit stuff in MP wordpress.   Just like Edwin and Emily have earned that Edit access, you to have it now with your work on MP 5.0.  Your log in name should be already in your gmail inbox with Emerson-Castaneda name. Please note that Wordpress doesn't accept ñ as it is a special character, so I had to settled for the N. Your name will appear publicly as Emerson Castañeda which is what we care about.

**Comment by aeiras** [comment]
I just got done with first review. I will be back tomorrow MicroProfilers to check on the comments and Q&A on feedback provided. :) Super fun stuff!

**Comment by TetianaFTV** [comment]
hi, I've made some edits / comments in blog article draft and presentation.

Possible text for a tweet:
MicroProfile 5.0 is now available! 📢🚀 Each specification included in this release has updated its dependencies from javax to jakarta. Learn more about recent changes and how to become fully @MicroProfileIO compatible [LINK]
@JakartaEE @jee_ambassadors

**Comment by ederks85** [comment]
@aeiras @emecas @Emily-Jiang I have updated the slides regarding the component specification release details in the PPT

**Comment by ederks85** [comment]
@Emily-Jiang I have also revied the blog's Google Doc. A lot was already commented on by Amelia, I have added a few of my own

**Comment by aeiras** [comment]
> hi, I've made some edits / comments in blog article draft and presentation.
> 
> Possible text for a tweet: MicroProfile 5.0 is now available! 📢🚀 Each specification included in this release has updated its dependencies from javax to jakarta. Learn more about recent changes and how to become fully @MicroProfileIO compatible [LINK] @jakartaee @jee_ambassadors

Hey Tetiana, 

If there is space, the tweet should start with #MicroProfileReleaseAnnouncement: 

Great write up, I suggest:

- inserting #JakartaEE 9.1 somewhere
- removing @jee_ambassadors - we must be careful to highlight any group within ecosystem. When we start, there is no stopping the "favoritism" and the lack of care for other groups that also have so much power within the technologies  that belong to the MP ecosystem. MP is not solely supportive of Jakarta.
-  insert #OSS hastag if there is space. 

Also, it is ok to keep 1 ticket for all tasks if those behind the activities wish them. However, there is a harder way to track stuff if using 1 ticket when the checklist welcomes each task to be a ticket to enable focus follow up, closing and tracking on check list.

**Comment by aeiras** [comment]
@ederks85 i reviewed the slides and adjusted a bunch of stuff. Sadly there is no suggestive mode in slides yet you could easily see them if checking History. 
Comments are insterted as well. Can you please take a look?

**Comment by ederks85** [comment]
@aeiras I have taken a look and will keep watching the document for new comments. @Emily-Jiang I have put a few comments on the <#8 slides. Are you still working on these?

**Comment by Emily-Jiang** [comment]
> hi, I've made some edits / comments in blog article draft and presentation.
> 
> Possible text for a tweet: MicroProfile 5.0 is now available! 📢🚀 Each specification included in this release has updated its dependencies from javax to jakarta. Learn more about recent changes and how to become fully @MicroProfileIO compatible [LINK] @jakartaee @jee_ambassadors

Thank you @TetianaFTV! I think we need to ask them to try it out the compatible implementation of Open Liberty 22.0.0.1-beta. I will provide some suggestions later today.

**Comment by Emily-Jiang** [comment]
@aeiras @TetianaFTV on a separate note, can you two help chasing up the votes on the releases - 4 voting threads to be closed. @TetianaFTV if you can cast your votes on the OpenAPI and MicroProfile 5.0? @aeiras can you get Tomitribe to vote on all of the ballots? Open API 3.0 and MicroProfile 5.0 need a lot of votes to come through before we can release MP 5.0 on 7th Dec.

**Comment by aeiras** [comment]
@Emily-Jiang, 

Yes on voting. TT will complete its review and voting today. Thank you for the care and extra push. We appreciate it.

**Comment by emecas** [comment]
@aeiras  at this stage,  do you think  it would be good idea to create a couple of GitHub issues for providing Spanish translation for both documents available here :

https://drive.google.com/drive/folders/1XqoNB9kEL9dpKxjHq71a4CfmBx1vjt3Z ? 

Mainly, in order to provide Spanish documentation for the release day!!! or would it be better wait until having the final versions of slides and blog post?

**Comment by aeiras** [comment]
+ 1 on starting the work on those translations, Emerson. We only have until Dec 17th before most of us go into recharge mode! 

Go for it! :)  You know the drill. We can include even a spanish blog, if you are up to it for Mp 5. release. We have never done it before. I think it could be a great new feature if there is ownership. :)

**Comment by Emily-Jiang** [comment]
> > hi, I've made some edits / comments in blog article draft and presentation.
> > Possible text for a tweet: MicroProfile 5.0 is now available! 📢🚀 Each specification included in this release has updated its dependencies from javax to jakarta. Learn more about recent changes and how to become fully @MicroProfileIO compatible [LINK] @jakartaee @jee_ambassadors
> 
@TetianaFTV how about the following tweet message
MicroProfile 5.0 is now available! 📢🚀 Each specification under MicroProfile 5.0 has updated its dependencies from javax to jakarta. Try it out using @OpenLibertyIO 22.0.0.1-beta https://openliberty.io/blog/2021/11/30/microprofile-5-22001-beta.html @MicroProfileIO @jakartaee @jee_ambassadors  [link to MP 5.0 blog]

**Comment by TetianaFTV** [comment]
Looks good but better leave just link to blog post in the tweet, in the article there can be added link to OpenLiberty

**Comment by aeiras** [comment]
Hey @Emily-Jiang & @TetianaFTV 

 

> Looks good but better leave just link to blog post in the tweet, in the article there can be added link to OpenLiberty

+1. The only link in the tweet is the MP blog.

**Comment by aeiras** [comment]
@Emily-Jiang, 
 I see why I confused you with the editors and authors feedback. 

Please see the pic attached. 
Under Authors, it only has your name. It needs to have 3 authors: you, Edwin and Emerson who are the Stewards of MP 5. release.  
I added Release category today. 

Please when you go into updating the blog with latest version, can you ensure that this blog has 3 authors? Only you can do it b/c you are the creator of the blog in WordPress. 

Thank you for rocking it!

![image](https://user-images.githubusercontent.com/10731224/144678693-22979b93-7e5d-404b-9b5b-f4eddab8adfd.png)

**Comment by Emily-Jiang** [comment]
> @Emily-Jiang, I see why I confused you with the editors and authors feedback.
> 
> Please see the pic attached. Under Authors, it only has your name. It needs to have 3 authors: you, Edwin and Emerson who are the Stewards of MP 5. release. I added Release category today.
> 
> Please when you go into updating the blog with latest version, can you ensure that this blog has 3 authors? Only you can do it b/c you are the creator of the blog in WordPress.
> 
> Thank you for rocking it!
> 
> ![image](https://user-images.githubusercontent.com/10731224/144678693-22979b93-7e5d-404b-9b5b-f4eddab8adfd.png)

I have updated the blog with the latest update from the google doc. As for the author addition, I don't know how, because there is no areas for me to add more authors. I am not sure whether it is possible. I had a quick look at the past blogs. I have not seen any blogs with multiple authors. I think it only uses the person who created the post. We can add the additional editors on the top if it helps. @aeiras please have a go at it by creating a testing post and see whether you can add additional authors.

**Comment by Emily-Jiang** [comment]
I am monitoring the voting status for MP 5.0 release. We are still awaiting AJUG and Garden State JUG to vote on OpenAPI 3.0 and MicroProfile 5.0 ballot. @aeiras if you can reach out and remind them to vote, it will be great. Thank you!

**Comment by aeiras** [comment]
> I am monitoring the voting status for MP 5.0 release. We are still awaiting AJUG and Garden State JUG to vote on OpenAPI 3.0 and MicroProfile 5.0 ballot. @aeiras if you can reach out and remind them to vote, it will be great. Thank you!

Notes sent- :)

**Comment by aeiras** [comment]
> > @Emily-Jiang, I see why I confused you with the editors and authors feedback.
> > Please see the pic attached. Under Authors, it only has your name. It needs to have 3 authors: you, Edwin and Emerson who are the Stewards of MP 5. release. I added Release category today.
> > Please when you go into updating the blog with latest version, can you ensure that this blog has 3 authors? Only you can do it b/c you are the creator of the blog in WordPress.
> > Thank you for rocking it!
> > ![image](https://user-images.githubusercontent.com/10731224/144678693-22979b93-7e5d-404b-9b5b-f4eddab8adfd.png)
> 
> I have updated the blog with the latest update from the google doc. As for the author addition, I don't know how, because there is no areas for me to add more authors. I am not sure whether it is possible. I had a quick look at the past blogs. I have not seen any blogs with multiple authors. I think it only uses the person who created the post. We can add the additional editors on the top if it helps. @aeiras please have a go at it by creating a testing post and see whether you can add additional authors.

It might be the new feature from WP that doesn't even allow authors to adjust the blog after it is saved. 

All good Emily. In the future we need to add **before saving the draft** before the blog is saved as authors whoever are the Stewards of the release. I will adjust the WP blog to separate editors from Stewards :) that should fix stuff! 

So fun and so exciting!   Please do rest. so late for you. 
See you on Monday and Tuesday (Jkta)

**Comment by caitmm43** [comment]
Emily confirmed that all needed approvals have been received & all materials are complete.  Just waiting on date to release. 

@rstjames - input needed to update homepage: change presentation, link to more info, and block with color-coded API's & updates.  He's on vacation until tomorrow 12/7.  @TetianaFTV will do as much as she can pending schedule conflict availability. 

For social media, use image already in media folder.  Source files are in drive.  Can update existing card to MP 5.0.  
@TetianaFTV will have designer update card tomorrow AM (Europe Time) and will push to hootsuite.  

Publish Social Media Updates: 1pm UK Time / 2pm Central European Time 
Go live for Emily: 2pm UK Time

**Comment by TetianaFTV** [comment]
There is still a set of comments in the presentation
https://docs.google.com/presentation/d/1PfXEOJzy8v2kGRudvknPox5elRasewv3MBeV0P4Rk6M/edit#slide=id.p

So is it ok to place it on site like this?

**Comment by TetianaFTV** [comment]
@Emily-Jiang for website update, correct links are required for 
- button in the first block with latest tag at home page https://microprofile.io/ (now I see only pre-releases in repo)
- each spec in this block
<img width="657" alt="Screenshot 2021-12-06 at 20 07 25" src="https://user-images.githubusercontent.com/38689227/144908526-34455d91-cf7f-471b-8809-5454c7185651.png">

**Comment by Emily-Jiang** [comment]
> There is still a set of comments in the presentation https://docs.google.com/presentation/d/1PfXEOJzy8v2kGRudvknPox5elRasewv3MBeV0P4Rk6M/edit#slide=id.p
> 
> So is it ok to place it on site like this?

I checked the comments and resolved them. Only one left was for making the logo pages prettier.

**Comment by Emily-Jiang** [comment]
> @Emily-Jiang for website update, correct links are required for
> 
>     * button in the first block with latest tag at home page https://microprofile.io/ (now I see only pre-releases in repo)
> 
>     * each spec in this block
> 
> 
> <img alt="Screenshot 2021-12-06 at 20 07 25" width="657" src="https://user-images.githubusercontent.com/38689227/144908526-34455d91-cf7f-471b-8809-5454c7185651.png">

Just for completeness, @TetianaFTV and I had a chat and I have supplied the links:
* https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html

* https://jakarta.ee/specifications/annotations/2.0/annotations-spec-2.0.html

* https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html

* https://jakarta.ee/specifications/jsonb/2.0/jakarta-jsonb-spec-2.0.html

* https://jakarta.ee/specifications/jsonp/2.0/apidocs/

* https://github.com/eclipse/microprofile-config/releases/tag/3.0

* https://github.com/eclipse/microprofile-fault-tolerance/releases/tag/4.0

* https://github.com/eclipse/microprofile-health/releases/tag/4.0

* https://github.com/eclipse/microprofile-jwt-auth/releases/tag/2.0

* https://github.com/eclipse/microprofile-metrics/releases/tag/4.0

* https://github.com/eclipse/microprofile-open-api/releases/tag/3.0

* https://github.com/eclipse/microprofile-opentracing/releases/tag/3.0

* https://github.com/eclipse/microprofile-rest-client/releases/tag/3.0

**Comment by TetianaFTV** [comment]
hi, is everything as planned?

@Emily-Jiang should this link be used as latest tag at home page?
https://github.com/eclipse/microprofile/releases/tag/5.0

**Comment by Emily-Jiang** [comment]
> hi, is everything as planned?
> 
> @Emily-Jiang should this link be used as latest tag at home page? https://github.com/eclipse/microprofile/releases/tag/5.0

yes

**Comment by TetianaFTV** [comment]
- website updated 
https://microprofile.io/
https://microprofile.io/resources/#presentation

- article published https://microprofile.io/2021/12/07/microprofile-5-0-release/

- social media posts live
https://twitter.com/MicroProfileIO/status/1468218811564318729
https://www.facebook.com/microprofile.io/photos/a.1256740654448487/4422063244582863
https://www.linkedin.com/feed/update/urn:li:activity:6873984503476432896

@aeiras can you please change the pinned tweet in MicroProfile Twitter account?

**Comment by Emily-Jiang** [comment]
Thank you @TetianaFTV ! This is awesome!

**Comment by caitmm43** [comment]
@Emily-Jiang, @emecas, @ederks85 , @aeiras, @TetianaFTV 

Hello all, can this ticket be closed?  Please add your comments here and update the minutes accordingly.  Thank you!  :)

**Comment by TetianaFTV** [comment]
yes, this ticket is completed
but i don't have the rights to close it

**Comment by caitmm43** [comment]
Done :)  Thank you, @TetianaFTV!
