### ISSUE TITLE
Hello all!  I will be volunteering as Marketing Steward for the Garden State JUG, November - December.  Excited to be joining this initiative!

### ISSUE THREAD

**Issue by caitmm43** [microprofile/microprofile-marketing#608]
- [ ]  Update MicroProfile presentation and save it in the right folder (technical person) [example here](https://github.com/eclipse/microprofile-marketing/issues/547) <br/>
- [ ] Import the presentation to the landing page and resources page of the website<br/>
- [ ] Draft a release announcement blog post using template (technical person) [example here](https://github.com/eclipse/microprofile-marketing/issues/548)<br/>
- [ ] Create release announcement design card [See example here](https://github.com/eclipse/microprofile-marketing/issues/546) <br/>
- [ ] Update MicroProfile homepage with release announcement design card<br/>
- [ ] Edit/Publish release announcement blog post on the MicroProfile Blog<br/>
- [ ] Announce release on social media using Hootsuite (Twitter, Linkedin, Facebook) [example here](https://github.com/eclipse/microprofile-marketing/issues/542)<br/>
- [ ] Write an update to the MP Community Forum about the release<br/>
- [ ] Update the MP Calendar with the Release Date (committer)

**Comment by Emily-Jiang** [comment]
@caitmm43 the github issue you opened is for MP releases. I think you need to open an issue without using the release template.

**Comment by caitmm43** [comment]
Thank you, @Emily-Jiang
