### ISSUE TITLE
Release MicroProfile 6.0

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#726]
MicroProfile 6.0 targets to be released on 5th Dec 2022.
- [x]  Update MicroProfile presentation and save it in the right folder (technical person) [example here](https://github.com/eclipse/microprofile-marketing/issues/547) <br/>
- [x] Import the presentation to the landing page and resources page of the website<br/>
- [x] Draft a release announcement blog post using template (technical person) [example here](https://github.com/eclipse/microprofile-marketing/issues/548)<br/>
- [x] Create release announcement design card [See example here](https://github.com/eclipse/microprofile-marketing/issues/546) <br/>
- [x] Update MicroProfile homepage with release announcement design card<br/>
- [x] Edit/Publish release announcement blog post on the MicroProfile Blog<br/>
- [x] Announce release on social media using Hootsuite (Twitter, Linkedin, Facebook) [example here](https://github.com/eclipse/microprofile-marketing/issues/542)<br/>
- [ ] Write an update to the MP Community Forum about the release<br/>
- [ ] Update the MP Calendar with the Release Date (committer)
- [ ] Add translations in Other languages (German, Russian, Spanish, etc) for the release blog

**Comment by rstjames** [comment]
@Emily-Jiang when will this go out and when should I start to make udates?

**Comment by Emily-Jiang** [comment]
> @Emily-Jiang when will this go out and when should I start to make udates?

Please see the top of the issue. It will go out on 5th Dec. All changes need to be made prior to that date. We can start working on in Nov.

**Comment by edbratt** [comment]
Please add translation tasks to the worksite above.

**Comment by emecas** [comment]
>> Please add translation tasks to the worksite above.

> Add translations in Other languages (German, Russian, Spanish, etc) for the release blog

- [x] German  #737
- [x] Russian  #736 
- [x] Spanish #738
- [ ] Portuguese  #739

- [x] Japanese #773

**Comment by rstjames** [comment]
Blog and presentation 6.o Drafted by @jclingan & @Emily-Jiang https://drive.google.com/drive/u/0/folders/1bPNVnkyXp8tu6Y-Q67o48BM4GPk5z6JL

**Comment by Emily-Jiang** [comment]
[Release blog for 6.0](https://docs.google.com/document/d/13lxIcazqJR6B4r97mdB35YrK543UYyTrWKVHd5FKwLc/edit?usp=share_link) is ready for review so that we can have it published by @rstjames next week. The [MP 6.0 presentation](https://docs.google.com/presentation/d/1zv84tq7SGRIpzPfxFQVAdVNT2jQvadjt/edit?usp=share_link&ouid=103606775052569552781&rtpof=true&sd=true) is here. Please review them asap. @aeiras @jclingan @edbratt

**Comment by rstjames** [comment]
@Emily-Jiang and @rstjames met last week to discuss what is needed to get done to release 6.0. 
Designs, SM and website update list.  + blog review

**Comment by m-reza-rahman** [comment]
Done my suggested changes, @rstjames. /cc @Emily-Jiang, @edbratt

**Comment by Emily-Jiang** [comment]
Proposed tweet message:
MP 6.0 Released and adopts the Jakarta EE 10 Core Profile! 📢🚀 It contains the new spec MP Telemetry 1.0 ( replacing MP OpenTracing) + MP Metrics 5.0 (major release) and other minor updates. Learn more about the release and how to become fully compatible https://microprofile.io/

@rstjames @aeiras feel free to update the above text

**Comment by Emily-Jiang** [comment]
@rstjames the blog post has been updated with the suggestions from @edbratt and @m-reza-rahman ! It is ready to go! Let's get them out on Tuesday!

**Comment by aeiras** [comment]
Thank you, @Emily-Jiang!

Reviewed media message is simplified to:
**#MicroProfileReleaseAnnouncement: #Microprofile 6.0 is released!  It adopts @JakartaEE 10 Core Profile📢🚀**

**Learn more [Link of blog]
https://microprofile.io/compatible/**

**#ByCommunityForCommunity #OpenSource**

@rstjames 
Please add the MP 6.0 https://microprofile.io/compatible/ 

----
The release cannot be announced tomorrow without an MP 6.0 compatible page.

**Comment by Emily-Jiang** [comment]
@rstjames you can add compatible page with the list of Open Liberty 22.0.0.13-beta,
[Certification Result ](https://openliberty.io/certifications/microprofile/6.0/22.0.0.13-beta-TCKResults.html)
[Download](https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/beta/22.0.0.13-beta/openliberty-22.0.0.13-beta.zip)
Java 11 and 17
Please reach out if you want me to double check the page @rstjames

**Comment by rstjames** [comment]
Social media is sent out. 
https://twitter.com/MicroProfileIO/status/1612780709004939264

Home page is updated: 
https://microprofile.io/

Compatible 6.0 page created
https://microprofile.io/compatible/6-0/

**Comment by aeiras** [comment]
beautiful work!!!

Let's keep this issue open as it is connected to the translation of the blog. :) 
--- 
@Emily-Jiang, 
We need to update the PR with an extra step, create a compatible page is a requirement. Do pull me in for review and merge if you have the bandwidth. If you cannot. I will automatically adjust the checklist and be done with it. Either work. :) Cheers.

**Comment by aeiras** [comment]
Closing the issue while 3 related focus on announcement translations:
https://github.com/eclipse/microprofile-marketing/issues/739
https://github.com/eclipse/microprofile-marketing/issues/737
https://github.com/eclipse/microprofile-marketing/issues/736

Spanish translation completed: https://github.com/eclipse/microprofile-marketing/issues/738
