### ISSUE TITLE
[Release]MicroProfile 6.1 release announcement

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#834]
- [x]  Update MicroProfile presentation and save it in the right folder (technical person) [example here](https://github.com/eclipse/microprofile-marketing/issues/547) <br/>
- [x] Import the presentation to the landing page and resources page of the website<br/>
- [x] Draft a release announcement blog post using template (technical person) [example here](https://github.com/eclipse/microprofile-marketing/issues/548)<br/>
- [x] Create release announcement design card [See example here](https://github.com/eclipse/microprofile-marketing/issues/546) <br/>
- [x] Update MicroProfile homepage with release announcement design card<br/>
- [x] Edit/Publish release announcement blog post on the MicroProfile Blog<br/>
- [x] Announce release on social media using Hootsuite (Twitter, Linkedin, Facebook) [example here](https://github.com/eclipse/microprofile-marketing/issues/542)<br/>
- [ ] Write an update to the MP Community Forum about the release<br/>
- [ ] Update the MP Calendar with the Release Date (committer)
- [ ] Translate the release blog in other lauguages such as (German,Russian, Spanish, etc)

**Comment by Emily-Jiang** [comment]
MP 6.1 slide [here](https://docs.google.com/presentation/d/1IVLaAIB0PrwEaUJQC8As5iuVqmLmPtGq/edit#slide=id.p1)

[MP 6.1 release folder](https://drive.google.com/drive/u/0/folders/1NpSIxyEa4jtA1c-gVqexuY07ij8SHnJb), which contains blogs and slides.

**Comment by Emily-Jiang** [comment]
The links to the building blocks are as follows:
[Jakarta EE 10 Core Profile](https://jakarta.ee/specifications/coreprofile/10/)
[MicroProfile Config 3.1](https://github.com/eclipse/microprofile-config/releases/tag/3.1)
[MicroProfile Fault Tolerance 4.0](https://github.com/eclipse/microprofile-fault-tolerance/releases/tag/4.0.2)
[MicroProfile Metrics 5.1](https://github.com/eclipse/microprofile-metrics/releases/tag/5.1.0)
[MicroProfile Health 4.0](https://github.com/eclipse/microprofile-health/releases/tag/4.0.1)
[MicroProfile Telemetry 1.1](https://github.com/eclipse/microprofile-telemetry/releases/tag/1.1)
[MicroProfile OpenAPI 3.1](https://github.com/eclipse/microprofile-open-api/releases/tag/3.1.1)
[MicroProfile JWT Authentication 2.1](https://github.com/eclipse/microprofile-jwt-auth/releases/tag/2.1)
[MicroProfile Rest Client 3.0](https://github.com/eclipse/microprofile-rest-client/releases/tag/3.0.1)

**Comment by Emily-Jiang** [comment]
MP 6.1 Compatible Page details [here](https://github.com/eclipse/microprofile-marketing/issues/836)

**Comment by Dexmaster** [comment]
Did building blocks on 6.1 draft.

**Comment by aeiras** [comment]
**Blog update review:**
Yesterday, during the Marketing call, 30 mins were used to review the blog by John, Ryan and Amelia. The API links lead to 405 errors. 

Editors in the blog adjusted :) Thank you, Emily.
